export const REQUEST_VIEWS = 'REQUEST_VIEWS';
export const RECEIVE_VIEWS_SUCCESS = 'RECEIVE_VIEWS_SUCCESS';
export const UPDATE_VIEW_DEF_LIST = 'UPDATE_VIEW_DEF_LIST';
export const RECEIVE_VIEWS_FAILURE = 'RECEIVE_VIEWS_FAILURE';
export const SET_SELECTED_VIEW = 'SET_SELECTED_VIEW';
export const REQUEST_TEMPLATE_TABLE = 'REQUEST_TEMPLATE_TABLE';
export const RECEIVE_TEMPLATE_TABLE_SUCCESS = 'RECEIVE_TEMPLATE_TABLE_SUCCESS';
export const RECEIVE_TEMPLATE_TABLE_FAILURE = 'RECEIVE_TEMPLATE_TABLE_FAILURE';

export const NEW_SELECTED_VIEW = 'NEW_SELECTED_VIEW';
export const UPDATE_SELECTED_VIEW = 'UPDATE_SELECTED_VIEW';
export const DELETE_TABLE_ROW = 'DELETE_TABLE_ROW';
export const SYNC_SELECTED_VIEW = 'SYNC_SELECTED_VIEW';
export const SAVE_VIEW_DEF = 'SAVE_VIEW_DEF';
export const DUPLICATE_VIEW_DEF = 'DUPLICATE_VIEW_DEF';
export const DELETE_VIEW_DEF = 'DELETE_VIEW_DEF';
export const OPEN_PREVIEW = 'OPEN_PREVIEW';
export const CLOSE_PREVIEW = 'CLOSE_PREVIEW';
export const ALERT_FORM = 'ALERT_FORM';
// ERROR
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const NEW_ERROR_READ = 'NEW_ERROR_READ';
