export const REQUEST_VIEWS = 'REQUEST_VIEWS';
export const RECEIVE_VIEWS_SUCCESS = 'RECEIVE_VIEWS_SUCCESS';
export const UPDATE_VIEW_DEF_LIST = 'UPDATE_VIEW_DEF_LIST';
export const RECEIVE_VIEWS_FAILURE = 'RECEIVE_VIEWS_FAILURE';
export const SET_SELECTED_VIEW = 'SET_SELECTED_VIEW';
export const UPDATE_SELECTED_VIEW = 'UPDATE_SELECTED_VIEW';
export const DELETE_TABLE_ROW = 'DELETE_TABLE_ROW';
export const SYNC_SELECTED_VIEW = 'SYNC_SELECTED_VIEW';
export const SAVE_VIEW_DEF = 'SAVE_VIEW_DEF';
export const DUPLICATE_VIEW_DEF = 'DUPLICATE_VIEW_DEF';
export const DELETE_VIEW_DEF = 'DELETE_VIEW_DEF';
export const OPEN_PREVIEW = 'OPEN_PREVIEW';
export const CLOSE_PREVIEW = 'CLOSE_PREVIEW';
export const NEW_SELECTED_VIEW = 'NEW_SELECTED_VIEW';

// Global message
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const RECEIVE_INFO = 'RECEIVE_INFO';
export const RECEIVE_WARNING = 'RECEIVE_WARNING';
export const MESSAGE_READ = 'MESSAGE_READ';
export const ALERT = 'ALERT';

export const LOAD_METADATA_DETAIL_SUCCESS = 'LOAD_METADATA_DETAIL_SUCCESS';
export const LOAD_ALL_METADATA_SUCCESS = 'LOAD_ALL_METADATA_SUCCESS';

// session
export const INIT = 'INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FORCE_LOGOUT = 'FORCE_LOGOUT';
export const STOP_MONITOR_EDIT = 'STOP_MONITOR_EDIT';
export const MONITOR_EDIT = 'MONITOR_EDIT';

// route
export const ROUTE_CHANGED = 'ROUTE_CHANGED';

// nav
export const NAV_RESPONSIVE = 'NAV_RESPONSIVE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const ADD_TOOL = 'ADD_TOOL';
export const REMOVE_TOOL = 'REMOVE_TOOL';

// ucmdb Adapter
export const ADAPTER_DATA_SUCCESS = 'ADAPTER_DATA_SUCCESS';
export const INTEGRATION_JOB_DATA_SUCCESS = 'INTEGRATION_JOB_DATA_SUCCESS';
export const INTEGRATION_JOB_ITEM_DATA_SUCCESS = 'INTEGRATION_JOB_ITEM_DATA_SUCCESS';
export const JOB_SELECT_SUCCESS = 'JOB_SELECT_SUCCESS';
export const ADAPTER_SIDEBAR_CLICK = 'ADAPTER_SIDEBAR_CLICK';
export const CLEAR_JOB_SELECTION = 'CLEAR_JOB_SELECTION';
export const CLEAR_JOB_ITEM_SELECTION = 'CLEAR_JOB_ITEM_SELECTION';

