/**
 * Created by huling on 11/23/2016.
 */
import {hpe as logo} from './logoImg.js';

const MODE = {
  CODE: 'Code',
  DESIGN: 'Design'
};

const init_style = {
  name: '',
  fontSize: 13,
  bold: false,
  margin: [0, 0, 0, 0],
  color: '#000000',
  italics: false
};

const table_style = [
  'noBorders', 'headerLineOnly', 'lightHorizontalLines'
];

const styles = {
  header: {
    bold: true,
    margin: [0, 0, 0, 10],
    italics: false,
    fontSize: 18,
    color: '#000000',
    tempId: -1
  },
  subheader: {
    fontSize: 16,
    bold: true,
    italics: false,
    margin: [0, 10, 0, 15],
    color: '#000000',
    tempId: -2
  },
  text: {
    margin: [0, 0, 0, 0],
    bold: false,
    italics: false,
    fontSize: 12,
    color: '#000000',
    tempId: -3
  },
  tableTitle: {
    margin: [0, 10, 0, 10],
    bold: true,
    italics: false,
    fontSize: 16,
    color: '#000000',
    tempId: -4
  },
  tableFields: {
    bold: false,
    margin: [0, 20, 20, 15],
    italics: false,
    fontSize: 13,
    color: '#000000',
    tempId: -5
  },
  tableExample: {
    bold: false,
    margin: [0, 5, 0, 15],
    italics: false,
    fontSize: 13,
    color: '#000000',
    tempId: -6
  },
  tableHeader: {
    bold: false,
    margin: [0, 0, 0, 0],
    italics: true,
    fontSize: 13,
    color: '#000000',
    tempId: -7
  },
  fieldTitle: {
    margin: [0, 0, 0, 0],
    italics: true,
    fontSize: 15,
    color: '#000000',
    bold: true,
    tempId: -8
  },
  fieldLabel: {
    italics: false,
    fontSize: 12,
    color: '#000000',
    bold: true,
    tempId: -9
  },
  fieldValue: {
    italics: false,
    fontSize: 12,
    color: '#000000',
    tempId: -10
  }
};

const defaultPDFDefinition = {
  header: {
    columns: [{
      width: '33%',
      text: 'left'
    }, {
      width: '33%',
      text: 'center',
      alignment: 'center'
    }, {
      width: '33%',
      text: 'right',
      alignment: 'right'
    }]
  },
  pageOrientation: 'portrait', //landscape
  content: [],
  footer: {
    columns: [{
      width: '33%',
      text: 'left'
    }, {
      width: '33%',
      text: 'center',
      alignment: 'center'
    }, {
      width: '33%',
      text: 'Date: @date',
      alignment: 'right'
    }]
  }
};

const defaultSettings = {
  styles: _.cloneDeep(styles),
  pageOrientation: 'portrait',
  pageHeader: {
    left: {text: 'Generated by AMB', style: 'text'},
    center: {text: '', style: 'text'},
    right: {text: '@logo', style: 'text'}
  },
  contents: {
    style: 'tableExample',
    layout: 'headerLineOnly',
    header: 'tableHeader',
    text: 'text',
    tableTitle: {
      style: 'tableTitle',
      text: '@tableTitle'
    }
  },
  fieldBlock: {
    label: 'fieldLabel',
    value: 'fieldValue',
    column: 2,
    fieldTitle: {
      style: 'fieldTitle',
      text: '@linkTitle'
    }
  },
  reportDesc: {
    text: '',
    style: 'subheader'
  },
  pageFooter: {
    left: {text: '', style: 'text'},
    center: {text: '', style: 'text'},
    right: {text:'Date: @date', style: 'text'}
  },
  reportHead:  {
    text: '@logo @title',
    style: 'header'
  },
  "images": {
    "@logo": logo
  }
};

const GLOBAL_VARIABLES = {
  TABLE_TITLE: '@tableTitle',
  LINK_TITLE: '@linkTitle',
  DATE: '@date',
  TITLE: '@title',
  LOGO: '@logo'
};

export {
  MODE,
  init_style,
  table_style,
  defaultPDFDefinition,
  defaultSettings,
  GLOBAL_VARIABLES
};
