/**
 * Created by huling on 11/23/2016.
 */

const MODE = {
  CODE: 'Code',
  DESIGN: 'Design'
};

const init_style = {
  name: '',
  fontSize: 13,
  bold: false,
  margin: [0, 0, 0, 0],
  color: '#000000',
  italics: false
};

const table_style = [
  'noBorders', 'headerLineOnly', 'lightHorizontalLines'
];

const styles = {
  header: {
    bold: true,
    margin: [0, 0, 0, 10],
    italics: false,
    fontSize: 18,
    color: '#000000',
    tempId: -1
  },
  subheader: {
    fontSize: 16,
    bold: true,
    italics: false,
    margin: [0, 10, 0, 15],
    color: '#000000',
    tempId: -2
  },
  text: {
    margin: [0, 0, 0, 0],
    bold: false,
    italics: false,
    fontSize: 12,
    color: '#000000',
    tempId: -3
  },
  tableTitle: {
    margin: [0, 10, 0, 10],
    bold: true,
    italics: false,
    fontSize: 16,
    color: '#000000',
    tempId: -4
  },
  tableFields: {
    bold: false,
    margin: [0, 20, 20, 15],
    italics: false,
    fontSize: 13,
    color: '#000000',
    tempId: -5
  },
  tableExample: {
    bold: false,
    margin: [0, 5, 0, 15],
    italics: false,
    fontSize: 13,
    color: '#000000',
    tempId: -6
  },
  tableHeader: {
    bold: false,
    margin: [0, 0, 0, 0],
    italics: true,
    fontSize: 13,
    color: '#000000',
    tempId: -7
  },
  fieldTitle: {
    margin: [0, 0, 0, 0],
    italics: true,
    fontSize: 15,
    color: '#000000',
    bold: true,
    tempId: -8
  },
  fieldLabel: {
    italics: false,
    fontSize: 12,
    color: '#000000',
    bold: true,
    tempId: -9
  },
  fieldValue: {
    italics: false,
    fontSize: 12,
    color: '#000000',
    tempId: -10
  }
};

const defaultPDFDefinition = {
  header: {
    columns: [{
      width: '33%',
      text: 'left'
    }, {
      width: '33%',
      text: 'center',
      alignment: 'center'
    }, {
      width: '33%',
      text: 'right',
      alignment: 'right'
    }]
  },
  pageOrientation: 'portrait', //landscape
  content: [],
  footer: {
    columns: [{
      width: '33%',
      text: 'left'
    }, {
      width: '33%',
      text: 'center',
      alignment: 'center'
    }, {
      width: '33%',
      text: 'Date: @date',
      alignment: 'right'
    }]
  }
};

const defaultSettings = {
  styles: _.cloneDeep(styles),
  pageOrientation: 'portrait',
  pageHeader: {
    left: {text: 'Generated by AMB', style: 'text'},
    center: {text: '', style: 'text'},
    right: {text: '', style: 'text'}
  },
  contents: {
    style: 'tableExample',
    layout: 'headerLineOnly',
    header: 'tableHeader',
    text: 'text',
    tableTitle: {
      style: 'tableTitle',
      text: '@tableTitle'
    }
  },
  fieldBlock: {
    label: 'fieldLabel',
    value: 'fieldValue',
    column: 2,
    fieldTitle: {
      style: 'fieldTitle',
      text: '@linkTitle'
    }
  },
  reportDesc: {
    text: '',
    style: 'subheader'
  },
  pageFooter: {
    left: {text: '', style: 'text'},
    center: {text: '', style: 'text'},
    right: {text:'Date: @date', style: 'text'}
  },
  reportHead:  {
    text: '@title',
    style: 'header'
  },
  "images": {
    "@logo": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAYAAADFeBvrAAACtUlEQVRoQ+2ZQXbSUBSG/z+eY4fiCsQVyA7EFSiTpo6gK7BdgJCkC6iuAByRdAKuQNxBXUFxBeLUQW5PcoBSDCEJ9yUcDcOcvP/d7/733ffyII7lF3jXgPQgWIDWJeyP0yKhscgg9TG+NyTR29QV4hyn/VHeuaoHSoBZQRSBqhbIdz+R/JDmQl6oaoFunBbEmhF4lgoFdrKuqWqBIooMUCIyx9ngZZb1VC5QFHzICSzp4NS5XQe4B0qA37D7jeMCioPmN4INgSxAeZMVSiAu7IFzPEAbMOsOlhFKIF9gDx619DQw8yWXAJMVKi9MpGsWKAVmL1TIHs4GF1nKbPMdc0AZYFKh8pIs3yfGV20wHJJsFtTAX6WRA2Yv1MRp4E/cTFqpe1XU2sU6J3z3rmqYByh8h91vrwPPCLMeLzInA0+qdOYhGPzASdhGx1nEz3LCrHQKA2mUmTZM3OW2HRK7n79RFFgzO2Fylst2/IcDVQgTO7K1ZA4H8t0pybc5EwuRrTWTV2DVptWBAvdXfD4TXMLCAqG0QLYIvN4VoxaMvkPB1TtCJomnYd+7JfFqG0oTRh9o+cWZeOYK3BHB7iaQNowJoHhTTvxMvvF6FAy1utmu8tVrCmOnScu6iyaSp+Hz9YYYPRg7TVhPuoTE3zAmnFlvpGpNwfcuSFwvAx7BCj9DrC4g7c1zl0kY3ZILvOhyI72TQWY4EeeRewXbs/GSSzoDishXgDNIOMV7Z64ce6Kc3hryveiSowHIFLRmWa+ZtCH1gLQjK6hXAxVMXGnDaodKS3XBiWqHCiautGH/n0OlpdbQRIVvfQzFc7AsEXiLff+gHTxLSQIi+Lm8CpYRiRclzWtkmggGwl7+Ozgj4eiJ1kB6uTSjVDtkJq96qrVDerk0o1Q7ZCaveqq1Q3q5NKP0zzl0D/Zt3TJq5S9jAAAAAElFTkSuQmCC"
  }
};

const GLOBAL_VARIABLES = {
  TABLE_TITLE: '@tableTitle',
  LINK_TITLE: '@linkTitle',
  DATE: '@date',
  TITLE: '@title',
  LOGO: '@logo'
};

export {
  MODE,
  init_style,
  table_style,
  defaultPDFDefinition,
  defaultSettings,
  GLOBAL_VARIABLES
};
