/**
 * Created by huling on 11/10/2016.
 */
import { getDisplayLabel, getFieldStrVal } from './RecordFormat';
import { loadRecordsByBody, getQueryByBody } from '../actions/explorer';

const MODE = {
  CODE: 'Code',
  DESIGN: 'Design'
};

const init_style = {
  name: '',
  fontSize: 16,
  bold: false,
  margin: [0, 0, 0, 0],
  color: '#000000',
  italics: false
};

const table_style = [
  'noBorders', 'headerLineOnly', 'lightHorizontalLines'
];

const styles = {
  header: {
    fontSize: 18,
    bold: true,
    margin: [0, 0, 0, 10],
    tempId: -1
  },
  subheader: {
    fontSize: 16,
    bold: true,
    margin: [0, 10, 0, 15],
    tempId: -2
  },
  text: {
    fontSize: 12,
    tempId: -3
  },
  tableFields: {
    margin: [0, 20, 20, 15],
    tempId: -4
  },
  tableExample: {
    margin: [0, 5, 0, 15],
    tempId: -5
  },
  tableHeader: {
    italics: true,
    fontSize: 13,
    color: '#000000',
    tempId: -6
  }
};

const defaultPDFDefinition = {
  header: {
    columns: [{
      width: '33%',
      text: 'left'
    }, {
      width: '33%',
      text: 'center',
      alignment: 'center'
    }, {
      width: '33%',
      text: 'right',
      alignment: 'right'
    }]
  },
  pageOrientation: 'portrait', //landscape
  content: [],
  footer: {
    columns: [{
      width: '33%',
      text: 'left'
    }, {
      width: '33%',
      text: 'center',
      alignment: 'center'
    }, {
      width: '33%',
      text: 'Date: @date',
      alignment: 'right'
    }]
  }
};

const defaultSettings = {
  styles: _.cloneDeep(styles),
  pageOrientation: 'portrait',
  pageHeader: {
    left: {text: 'Generated by AMB', style: 'text'},
    center: {text: '', style: 'text'},
    right: {text: '', style: 'text'}
  },
  contents: {
    style: 'tableExample',
    layout: 'headerLineOnly',
    header: 'tableHeader',
    text: 'text'
  },
  reportDesc: {
    text: '',
    style: 'subheader'
  },
  pageFooter: {
    left: {text: '', style: 'text'},
    center: {text: '', style: 'text'},
    right: {text:'Date: @date', style: 'text'}
  },
  reportHead:  {
    text: '@title',
    style: 'header'
  }
};

const genTable = ({title, records, fields, style = {layout: 'headerLineOnly', header: 'tableHeader', text: 'text', title: 'tableHeader'}}) => {
  if (!records)
    return [];

  const body = [];
  body.push(fields.map((field, index) => (
  {text: getDisplayLabel(field), style: style.header}
  )));

  records.map((record) => {
    const row = [];
    fields.map((field, tdindex) => (
      row.push({text: getFieldStrVal(record, field), style: style.text})
    ));
    body.push(row);
  });

  return [{
    text: `${title} (${records.length})`, style: style.title
  }, {
    style: style.style,
    table: {
      headerRows: 1,
      body: body
    },
    layout: style.layout
  }];
};

const analyzeRecordList = (title, filter, allFields, records, style) => {
  let availableFields = [];
  if (filter.length > 0) {
    allFields.map(field => {
      for (let f of filter) {
        if (field.sqlname.toLowerCase() == f.toLowerCase()) {
          availableFields.push(field);
          break;
        }
      }
    });
  }

  if (availableFields.length == 0) {
    availableFields = allFields;
  }

  return genTable({title, records, fields: availableFields, style});
};

function getLinkData(link, pdf_link = []) {
  const title = link.label;
  const fields = link.body.fields;
  link.body.param = {};

  return loadRecordsByBody(link.body).then(data => {
    const links = link.body.links;
    const promises = [];
    if (links && links.length > 0) {
      const pdf_ol = [];

      pdf_link.push({
        text: `${title} (${data.count})`, style: 'subheader'
      });

      pdf_link.push({
        ol: pdf_ol,
        margin: [20, 0, 0, 0]
      });

      data.entities.map((record) => {
        let summary = {
          stack: [
            {text: record.self, style: 'tableHeader'},
            {
              alignment: 'justify',
              columns: genSummary(record, fields)
            }
          ],
          margin: [0, 0, 0, 40]
        };
        pdf_ol.push(summary);

        links.forEach((sub_link) => {
          sub_link.body.params = getQueryByBody(getLinkBody(sub_link, record));
          promises.push(getLinkData(sub_link, summary.stack));
        });
      });
    } else {
      pdf_link.push(genTable({title, records: data.entities, fields}));
    }
    return Promise.all(promises);
  });
}

function getLinkBody(link, record) {
  var body = Object.assign({}, link.body);

  let AQL = "";
  if (link.src_field) {
    var relative_path = link.src_field.relative_path;
    var src_field = relative_path ? relative_path + '.' + link.src_field.sqlname : link.src_field.sqlname;
    if (record[src_field]) {
      AQL = `${link.dest_field.sqlname}=${record[src_field]}`;
    }
  }

  body.filter = body.filter ? `(${body.filter}) AND ${AQL}` : AQL;
  return body;
}

function genSummary(record, fields) {
  var pdf_header = [{}, {}];

  fields.forEach((field, index) => {
    var column = !(index % 2) ? pdf_header[0] : pdf_header[1];
    if (!column.table)
      Object.assign(column, {
        layout: 'noBorders',
        style: 'tableFields',
        table: {
          widths: ['auto', '*'],
          body:[]
        }
      });

    column.table.body.push([
      {text: getDisplayLabel(field), bold: true},
      getFieldStrVal(record, field, true)
    ]);
  });

  return pdf_header;
}

const analyzeTitle = (text, title) => {
  if (text.toLowerCase().includes('@title')) {
    return text.replace(/@title/gi, title);
  }

  return text;
};

const analyzeDate = (text, date) => {
  if (text.toLowerCase().includes('@date')) {
    return text.replace(/@date/gi, date);
  }

  return text;
};

const getPreviewStyle = (style = null, ignoreMargin = false) => {
  const previewStyle = {};
  if (style) {
    const {bold=false, italics=false, color='#000000', margin=[0, 0, 0, 0], fontSize=16} = style;
    previewStyle.fontWeight = bold ? 'bold' : 'normal';
    previewStyle.fontStyle = italics ? 'italic' : 'normal';
    previewStyle.fontSize = fontSize;
    previewStyle.color = color;

    if (!ignoreMargin) {
      previewStyle.margin = margin.slice(1).join('px ') + 'px ' + margin[0] + 'px';
    }
  }
  return previewStyle;
};

const updateValue = (event, {state, callback, val = event.target.value, name = event.target.name, type = event.target.type}) => {
  if (type == 'range' || type == 'number') {
    val = parseInt(val);
  } else if (type == 'checkbox') {
    val = event.target.checked;
  }

  if (name.indexOf('.') > -1) {
    const nameParts = name.split('.');
    nameParts.reduce((state, key, index) => {
      if (index == nameParts.length - 1) {
        state[key] = val;
      }
      return state[key];
    }, state);
  } else {
    state[name] = val;
  }

  if (typeof callback == 'function') {
    callback();
  }
};

const getPdfLine = (label, {text='', style=''}) => {
  let result = analyzeTitle(text, label);

  const date = (new Date()).toLocaleDateString();
  result = analyzeDate(result, date);
  return {
    text: result, style
  };
};

const setTextLine = (target, source, label) => {
  const textObj = getPdfLine(label, source);
  target.text = textObj.text;
  target.style = textObj.style;
};

const translateText = (pdfDefinition, {settings, records, fields_state, body, record, links}) => {
  const {fields: fields_props = [], label = ''} = body;
  //const fieldsName = fields_state.filter(field => field.selected).map(field => field.sqlname);
  const fieldsName = fields_state.map(field => field.sqlname);

  const content = [];

  content.push(getPdfLine(label, settings.reportHead));
  content.push(getPdfLine(label, settings.reportDesc));
  if (records.length > 0) {
    content.push(analyzeRecordList(body.label, fieldsName, fields_props, records, settings.contents));
  }

  const promiseList = [];
  if (links && links.length > 0) {

    content.push(genSummary(record, fields_props));

    links.forEach(link => {
      promiseList.push(getLinkData({...link, param: {}}, content));
    });
  }

  return Promise.all(promiseList).then(() => {
    pdfDefinition.content = content;

    setTextLine(pdfDefinition.header.columns[0], settings.pageHeader.left, label);
    setTextLine(pdfDefinition.header.columns[1], settings.pageHeader.center, label);
    setTextLine(pdfDefinition.header.columns[2], settings.pageHeader.right, label);

    setTextLine(pdfDefinition.footer.columns[0], settings.pageFooter.left, label);
    setTextLine(pdfDefinition.footer.columns[1], settings.pageFooter.center, label);
    setTextLine(pdfDefinition.footer.columns[2], settings.pageFooter.right, label);

    pdfDefinition.pageOrientation = settings.pageOrientation;
    pdfDefinition.styles = settings.styles;
    return pdfDefinition;
  });
};

const format = (pdfDefinition) => {
  if (typeof pdfDefinition == 'string') {
    return pdfDefinition;
  }
  const text = JSON.stringify(pdfDefinition);
  let spliters = 0, result = '', inArray = false, splitted = false;
  for (let char of text) {
    result += char;
    if (char == '[') {
      inArray = true;
    } else if (char == ']') {
      inArray = false;
    }
    if (splitted) {
      splitted = false;
      continue;
    }

    if (char == '{') {
      result += '\n' + '\t'.repeat(++spliters);
      splitted = true;
    } else if (char == '}') {
      result = result.slice(0, -1);
      result += '\n' + '\t'.repeat(--spliters);
      result += char;
    } else if (char == ',' && !inArray) {
      result += '\n' + '\t'.repeat(spliters);
      splitted = true;
    }
  }

  return result;
};

const download = ({onBefore, props, getPDFDefinition, onDone}) => {
  onBefore();
  const {body, recordsStart: offset, limit, name = body.label} = props;
  body.param = {offset,limit};

  loadRecordsByBody(body).then((data) => {
    const pdfDefinition = getPDFDefinition(data.entities);
    if (pdfDefinition) {
      pdfMake.createPdf(pdfDefinition).download(name + '.pdf');
      onDone();
    }
  });
};

const preview = (pdfDefinition, callBack) => {
  pdfMake.createPdf(pdfDefinition).getDataUrl((outDoc) => {
    const pdfContainer = document.getElementById('pdfContainer');
    if (pdfContainer) {
      const lastPDF = document.getElementById('pdfV');
      if (lastPDF) {
        lastPDF.remove();
      }

      const pdfContent = document.createElement('embed');
      pdfContent.id = 'pdfV';
      pdfContent.width = '100%';
      pdfContent.height = '100%';
      pdfContent.src = outDoc;

      document.getElementById('pdfContainer').appendChild(pdfContent);

      if (typeof callBack == 'function') {
        callBack();
      }
    }
  });
};

export {
  MODE,
  init_style,
  table_style,
  styles,
  defaultPDFDefinition,
  analyzeRecordList,
  getPreviewStyle,
  updateValue,
  translateText,
  format,
  download,
  preview,
  defaultSettings,
  getLinkData,
  genSummary
};
